In [1]:
import numpy as np

In [2]:
num_points = 20

X_train = np.random.rand(num_points, 2)
y_train = np.array([1 if point[0] > point[1] else 0 for point in X_train])

print("Generated training set (X):\n", X_train)
print("\nLabels (y):\n", y_train)

Generated training set (X):
 [[0.70481408 0.97364621]
 [0.43826158 0.32437728]
 [0.37083955 0.10698302]
 [0.52432684 0.20791007]
 [0.16134804 0.88757536]
 [0.49990188 0.37026859]
 [0.16876368 0.05414295]
 [0.85540896 0.19662959]
 [0.30947042 0.93948706]
 [0.18801887 0.08015314]
 [0.7616835  0.60996924]
 [0.23077492 0.76475562]
 [0.72191172 0.80593202]
 [0.13590355 0.83780989]
 [0.02582931 0.72001395]
 [0.16060989 0.71536748]
 [0.88414694 0.19580915]
 [0.22952287 0.44960141]
 [0.32760502 0.50232561]
 [0.53707323 0.15559188]]

Labels (y):
 [0 1 1 1 0 1 1 1 0 1 1 0 0 0 0 0 1 0 0 1]


In [3]:
class Perceptron:

    def __init__(self, learning_rate=0.01, n_iters=1000):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.activation_func = self._sigmoid
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape

        # Initialize parameters
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.n_iters):
            for idx, x_i in enumerate(X):
                linear_output = np.dot(x_i, self.weights) + self.bias
                y_predicted = self.activation_func(linear_output)

                # Perceptron update rule
                update = self.lr * (y[idx] - y_predicted)

                self.weights += update * x_i
                self.bias += update

    def predict(self, X):
        linear_output = np.dot(X, self.weights) + self.bias
        y_predicted = self.activation_func(linear_output)
        return np.where(y_predicted >= 0.5, 1, 0)

    def _sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def accuracy(self, y_true, y_pred):
        accuracy = np.sum(y_true == y_pred) / len(y_true)
        return accuracy


Training on 20 datapoints

In [4]:
model = Perceptron()
model.fit(X_train, y_train)

a). Testing on 1000 datapoints




In [5]:
X_test = np.random.rand(1000, 2)
y_test = np.array([1 if point[0] > point[1] else 0 for point in X_test])

print("Generated testing set (X):\n", X_test)
print("\nLabels (y):\n", y_test)

Generated testing set (X):
 [[0.61393666 0.14809921]
 [0.06025393 0.17730076]
 [0.82399621 0.73737071]
 ...
 [0.62022031 0.35394346]
 [0.12725233 0.11263853]
 [0.23580809 0.77214778]]

Labels (y):
 [1 0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 0
 1 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0
 0 1 1 1 1 0 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1
 0 1 1 1 0 0 1 0 0 0 1 1 1 1 1 0 0 1 1 0 0 1 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1
 1 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 0 1 0 0 1 1 1 0 0 0 0 1
 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0
 0 0 0 1 1 0 0 1 0 1 1 1 0 1 0 0 0 0 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 1
 1 0 0 1 0 1 1 0 1 0 0 1 1 1 1 1 0 1 0 1 0 0 1 1 1 0 1 0 1 1 1 1 0 1 0 0 1
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1
 0 1 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0 1 0 0 1 1 0 0 1
 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 0 0 1 0 1 1 0 0 0 0

In [6]:
predictions = model.predict(X_test)

print("Accuracy on the test data:", model.accuracy(y_test, predictions))

Accuracy on the test data: 0.909


b). Training with Hinge Loss.

In [7]:
class Perceptron_Hinge:

    def __init__(self, learning_rate=0.01, n_iters=1000):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.activation_func = self._sigmoid
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape

        # Initialize parameters
        self.weights = np.zeros(n_features)
        self.bias = 0

        y_ = np.array([1 if i > 0 else -1 for i in y])  # Convert y to {-1, 1}

        for _ in range(self.n_iters):
            for idx, x_i in enumerate(X):
                linear_output = np.dot(x_i, self.weights) + self.bias
                y_predicted = self.activation_func(linear_output)

                # Hinge loss update rule
                loss = max(0, 1 - y_[idx] * linear_output)
                if loss > 0:  # Update only when there's a loss
                    update = self.lr * y_[idx] * x_i
                    self.weights += update
                    self.bias += self.lr * y_[idx]

    def predict(self, X):
        linear_output = np.dot(X, self.weights) + self.bias
        y_predicted = self.activation_func(linear_output)
        return np.where(y_predicted >= 0.5, 1, 0)

    def _sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def accuracy(self, y_true, y_pred):
        accuracy = np.sum(y_true == y_pred) / len(y_true)
        return accuracy


In [8]:
model = Perceptron_Hinge()
model.fit(X_train, y_train)

In [9]:
predictions = model.predict(X_test)
print("Accuracy on the test data:", model.accuracy(y_test, predictions))

Accuracy on the test data: 0.943
